Remove curl from Dockerfile-golang1.26.build-tools
curl is already installed with ubi10 and the change from curl-minimal
to curl fails with:

--> 1d4cd68d645d
STEP 13/28: RUN dnf swap -y curl-minimal curl
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 10 (RPMs) - BaseOS 1.0 MB/s | 180 kB     00:00
Red Hat Universal Base Image 10 (RPMs) - AppStr 2.4 MB/s | 400 kB     00:00
Red Hat Universal Base Image 10 (RPMs) - CodeRe 230 kB/s |  27 kB     00:00
Package curl-8.12.1-4.el10_2.4.x86_64 is already installed.
Error:
 Problem: cannot install the best candidate for the job
  - conflicting requests
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: building at STEP "RUN dnf swap -y curl-minimal curl": while running runtime: exit status 1

Signed-off-by: Martin Schuppert <mschuppert@redhat.com>