Heat Stack name Optimization
So far, we were using ${GITHUB_SHA:0:7} in heat stack name,
${GITHUB_SHA} gives merged hash. In scenarios where we have parallel
PR for same operator this could issue because heat stack with
same name is already created.

~~~
ERROR: The Stack (gha_sno_stack_a148a37) already exists.
~~~

With this patch we are changing naming convention of stack to include
operator name and PR number to avoid duplicate stack name.